// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

import (
	"time"
)

// Error エラーメッセージモデル
type Error struct {
	Message string `json:"message"`
}

// Image コンテナイメージモデル
type Image struct {
	Digest         string    `json:"digest"`
	PushedAt       time.Time `json:"pushed_at"`
	RepositoryName string    `json:"repository_name"`
	Size           float32   `json:"size"`
	Tags           []string  `json:"tags"`
}

// ImageTag defines model for ImageTag.
type ImageTag struct {
	Tag string `json:"tag"`
}

// ErrorResponse エラーメッセージモデル
type ErrorResponse = Error

// ImagesResponse defines model for imagesResponse.
type ImagesResponse = []Image

// ImagesRequest defines model for imagesRequest.
type ImagesRequest = ImageTag

// PostImagesJSONRequestBody defines body for PostImages for application/json ContentType.
type PostImagesJSONRequestBody = ImageTag
